version: 2.1

jobs:
  begin_workflow:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Instalar dependencias de correo
          command: cd reactapp && npm install nodemailer
      - run:
          name: Enviar correo de inicio
          command: cd reactapp && node scripts/begin_workflow.js

  test:
    docker:
      - image: cimg/node:14.17
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            cd reactapp
            npm install
            # Dividir las pruebas usando una herramienta adecuada
            npm run test -- --shard $(CIRCLE_NODE_INDEX) --shards $(CIRCLE_NODE_TOTAL)
      - run:
          name: Enviar correo de testing
          command: cd reactapp && node scripts/begin_testing.js  

  build:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: cd reactapp && npm install
      - run:
          name: Construir la aplicaci贸n
          command: cd reactapp && npm run build
      - run:
          name: Enviar correo de build
          command: cd reactapp && node scripts/begin_build.js     


  deploy:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Instalar dependencias de correo
          command: cd reactapp && npm install nodemailer
      - run:
          name: Desplegar la aplicaci贸n
          command: cd reactapp && echo "Desplegando la aplicaci贸n!"
      - run:
          name: Enviar correo de deploy
          command: cd reactapp && node scripts/begin_deploy.js  


  commit_other_branch:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Instalar dependencias de correo
          command: cd reactapp && npm install nodemailer
      - run:
          name: Enviar notificaci贸n de Pull Request
          command: cd reactapp && node scripts/commit_notification.js

workflows:
  version: 2

  first_workflow:
    jobs:
      - begin_workflow:
          filters:
              branches:
                only: main
      - test:
          requires:
            - begin_workflow
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build

  second_workflow:
    jobs:
      - commit_other_branch:
          filters:
            branches:
              ignore: main
